apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: gridfire-prod
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: csleary/gridfire-api
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: 128Mi
              cpu: 25m
            limits:
              memory: 1.5Gi
              cpu: 1000m
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: amqp-config
            - configMapRef:
                name: api-config
            - configMapRef:
                name: contracts-config
            - configMapRef:
                name: ipfs-config
            - configMapRef:
                name: network-config
            - secretRef:
                name: api-secrets
            - secretRef:
                name: aws-secrets
            - secretRef:
                name: mongodb-uri
            - secretRef:
                name: rabbitmq-user
          startupProbe:
            httpGet:
              path: /livez
              port: 5000
          livenessProbe:
            httpGet:
              path: /livez
              port: 5000
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
      imagePullSecrets:
        - name: regcred
