apiVersion: apps/v1
kind: Deployment
metadata:
  name: gridfire-client
  namespace: gridfire-prod
  labels:
    app: gridfire-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gridfire-client
  template:
    metadata:
      labels:
        app: gridfire-client
    spec:
      containers:
        - name: gridfire-client
          image: csleary/gridfire-client
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 128Mi
              cpu: 25m
            limits:
              memory: 1Gi
              cpu: 1000m
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: gridfire-client
  namespace: gridfire-prod
spec:
  selector:
    app: gridfire-client
  ports:
    - port: 80
