apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: csleary@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: csleary@gmail.com
    privateKeySecretRef:
      name: letsencrypt-production-key
    solvers:
      - dns01:
          webhook:
            groupName: gridfire.app
            solverName: hetzner
            config:
              secretName: hetzner-secret
              # zoneName: gridfire.app
              apiUrl: https://dns.hetzner.com/api/v1
---
apiVersion: v1
kind: Secret
metadata:
  name: hetzner-secret
  namespace: cert-manager
type: Opaque
data:
  api-key: YjFSVWw0eVpSNVNETGRUN1pXdVhuaE9zSkRRTUd2WEk=
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: cert-manager
spec:
  commonName: gridfire.app
  dnsNames:
    - gridfire.app
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  secretName: tls-secret
