apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: gridfire-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gridfire-prod
  name: continuous-deployment
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: continuous-deployment
  namespace: gridfire-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: continuous-deployment
subjects:
  - kind: ServiceAccount
    name: github-actions
    namespace: gridfire-prod
---
apiVersion: v1
kind: Secret
metadata:
  name: github-actions-token
  annotations:
    kubernetes.io/service-account.name: github-actions
type: kubernetes.io/service-account-token
