apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipfs-node
  namespace: gridfire-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs-node
  serviceName: ipfs-node
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: ipfs-node
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ipfs-node
          image: csleary/ipfs-node
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
            - containerPort: 5001
            - containerPort: 8080
          volumeMounts:
            - name: ipfs-data
              mountPath: /data/ipfs
      imagePullSecrets:
        - name: regcred
  volumeClaimTemplates:
    - metadata:
        name: ipfs-data
      spec:
        accessModes: ["ReadWriteOncePod"]
        storageClassName: hcloud-volumes
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-node
  namespace: gridfire-prod
spec:
  selector:
    app: ipfs-node
  ports:
    - name: p2p
      port: 4001
    - name: rpc
      port: 5001
    - name: gateway
      port: 8080
