apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: gridfire-prod
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.10.0-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq/mnesia
          resources:
            requests:
              memory: 128Mi
              cpu: 25m
            limits:
              memory: 1Gi
              cpu: 250m
          envFrom:
            - configMapRef:
                name: rabbitmq-config
            - secretRef:
                name: rabbitmq-user
  volumeClaimTemplates:
    - metadata:
        name: rabbitmq-data
      spec:
        accessModes: ["ReadWriteOncePod"]
        storageClassName: hcloud-volumes
        resources:
          requests:
            storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: gridfire-prod
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: amqp
      targetPort: 5672
    - port: 15672
      name: management
      targetPort: 15672
