apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: gridfire-prod
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: csleary/gridfire-worker
          imagePullPolicy: Always
          resources:
            requests:
              memory: 128Mi
              cpu: 25m
            limits:
              memory: 1.5Gi
              cpu: 1000m
          envFrom:
            - configMapRef:
                name: amqp-config
            - configMapRef:
                name: worker-config
            - secretRef:
                name: aws-secrets
            - secretRef:
                name: mongodb-uri
            - secretRef:
                name: rabbitmq-user
          ports:
            - containerPort: 9090
          startupProbe:
            tcpSocket:
              port: 9090
          readinessProbe:
            tcpSocket:
              port: 9090
          livenessProbe:
            tcpSocket:
              port: 9090
      imagePullSecrets:
        - name: regcred
