apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: gridfire-prod
spec:
  selector:
    app: rabbitmq
  ports:
    - port: 5672
      name: amqp
      targetPort: 5672
    - port: 15672
      name: management
      targetPort: 15672
