grafana:
  persistence:
    enabled: true
    type: sts
    storageClassName: "hcloud-volumes"
    accessModes:
      - ReadWriteOnce
    size: 20Gi
    finalizers:
      - kubernetes.io/pvc-protection
