name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - "docker/Dockerfile.api"
      - "apps/api/**"
      - "apps/shared/**"
      - ".github/workflows/docker-build-api.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          tags: csleary/gridfire-api:$(date +%s)
