name: build-api

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "docker/Dockerfile.api"
      - "apps/api/**"
      - "shared/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          tags: csleary/gridfire-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_URL }}
          k8s-secret: ${{ secrets.K8S_SA_TOKEN }}
      - uses: actions/checkout@v4
      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v5
        with:
          namespace: default
          manifests: |
            manifests/production/api.yaml
          images: |
            csleary/gridfire-api:${{ github.sha }}
