name: build worker

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "docker/Dockerfile.worker"
      - "apps/worker/**"
      - "shared/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: docker/Dockerfile.worker
          push: true
          tags: csleary/gridfire-worker:${{ github.sha }}
